# Generated by Django 5.0.6 on 2024-05-13 00:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('book_grp', models.IntegerField(default=0)),
                ('intro', models.CharField(max_length=512)),
                ('rule', models.CharField(max_length=256)),
                ('word_count', models.IntegerField(default=0)),
                ('total_chapter_num', models.IntegerField(default=0)),
                ('first_chapter_title', models.CharField(max_length=64)),
                ('last_chapter_title', models.CharField(max_length=64)),
                ('uploader', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('share', models.BooleanField(default=False)),
                ('charset', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BookGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('book_id', models.IntegerField()),
                ('book_url', models.CharField(max_length=256)),
                ('index', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('chapter_id', models.IntegerField()),
                ('words_read', models.IntegerField()),
                ('content', models.TextField()),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('chapter_id', models.IntegerField()),
                ('read_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('words_read', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('font_size', models.IntegerField(default=16)),
                ('read_bg', models.CharField(default='#fff', max_length=256)),
            ],
        ),
    ]
