# Generated by Django 5.0.6 on 2024-05-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_chapter_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='last_chapter_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
