# Generated by Django 4.0.5 on 2022-06-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_book_fist_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='fist_chapter',
            new_name='first_chapter',
        ),
    ]
