# Generated by Django 4.0.5 on 2022-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_rename_fist_chapter_book_first_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_chapter',
            field=models.IntegerField(null=True),
        ),
    ]
