# Generated by Django 4.0.5 on 2022-06-22 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_alter_book_first_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.IntegerField(default=0),
        ),
    ]
