# Generated by Django 4.0.5 on 2022-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_book_upload_time_book_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('chapter_id', models.IntegerField()),
                ('words_read', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='novel_type',
            new_name='book_type',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='novel_id',
            new_name='book_id',
        ),
    ]
