# Generated by Django 4.0.5 on 2022-06-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_userbookrecord_rename_novel_type_book_book_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_chapter',
            field=models.IntegerField(default=1),
        ),
    ]
