# Generated by Django 4.0.5 on 2022-07-01 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_alter_book_first_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrecord',
            name='read_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
