# Generated by Django 4.0.5 on 2022-07-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_userbookrecord_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('font_size', models.IntegerField(default=16)),
                ('read_bg', models.CharField(default='#fff', max_length=256)),
            ],
        ),
    ]
