# Generated by Django 4.0.5 on 2022-07-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_usersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('words_read', models.IntegerField()),
            ],
        ),
    ]
