# Generated by Django 4.0.5 on 2022-07-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_userbookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookMark',
        ),
    ]
