# Generated by Django 4.0.5 on 2022-07-28 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0014_userbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmark',
            name='read_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
