# Generated by Django 4.0.5 on 2022-07-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0015_userbookmark_read_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookmark',
            old_name='read_time',
            new_name='add_time',
        ),
    ]
